version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    target-branch: "mainline"
    open-pull-requests-limit: 20
    
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: daily
    target-branch: "mainline"
    open-pull-requests-limit: 20
