name: CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ "mainline" ]
    paths-ignore:
      - "README.md"
  push:
    branches: [ "mainline" ]
    paths-ignore:
      - "README.md"

permissions:
  contents: read

jobs:
  ci:
    name: ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:

          # MUSL Targets
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
          - os: ubuntu-latest
            target: arm-unknown-linux-musleabihf
          - os: ubuntu-latest
            target: armv7-unknown-linux-musleabihf
          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
          
          # Darwin targets
          - os: macos-latest
            target: x86_64-apple-darwin
        # - os: macos-latest
        #   target: aarch64-apple-darwin

          # Windows targets
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            triplet: x64-windows-static-md
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            triplet: arm64-windows-static-md

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: ${{ matrix.target }}

      - name: Setup cache
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}

      - name: Install xz, protobuf for MacOS
        if: runner.os == 'macOS'
        run: brew install xz protobuf

      - name: Install cmake on Windows
        if: runner.os == 'Windows'
        uses: lukka/get-cmake@latest

      - name: Install protoc on Windows
        if: runner.os == 'Windows'
        uses: arduino/setup-protoc@v2

      - name: Install vcpkg on windows
        if: runner.os == 'Windows'
        uses: lukka/get-cmake@latest
        with:
          vcpkgDirectory: C:/vcpkg
          doNotUpdateVcpkg: true

      - name: Install liblzma on windows
        if: runner.os == 'Windows'
        run: |
          ${{ env.RUNVCPKG_VCPKG_ROOT }}/vcpkg.exe install liblzma --triplet ${{ matrix.triplet }}

      - name: Build binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --locked --target=${{ matrix.target }} --color=always --verbose
          use-cross: ${{ runner.os == 'Linux' }}

      - name: Package for (*nix)
        if: runner.os != 'Windows'
        run: >
          tar -cv
          LICENSE README.md
          -C target/${{ matrix.target }}/release/ otadump
          | gzip --best
          > 'otadump-${{ steps.get_version.outputs.value }}-${{ matrix.target }}.tar.gz'
          
      - name: Package for (Windows)
        if: runner.os == 'Windows'
        run: >
          7z a 'otadump-${{ steps.get_version.outputs.value }}-${{ matrix.target }}.zip'
          LICENSE README.md
          ./target/${{ matrix.target }}/release/otadump.exe
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: |
            *.deb
            *.tar.gz
            *.zip
      
